{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListStorageLensConfigurations",
        "s3:GetStorageLensConfiguration",
        "s3:GetStorageLensDashboard"
      ],
      "Resource": "*"
    }
  ]
}
